config/routes.rb
Batables::Application.routes.draw do
  get "log_in" => "sessions#new", :as => "log_in"
  post 'sessions', to: 'sessions#create', as: 'sessions'
  delete "log_out" => "sessions#destroy", :as => "log_out"

  resources :users

  root to: 'sessions#new'
end

app/models/user.rb
class User < ActiveRecord::Base
  before_save { self.email = email.downcase }

  has_secure_password

  validates :password, :password_confirmation, presence: true, on: :create
  validates :password, length: { minimum: 6 }, on: :create
  validates :first_name, :last_name, presence: true
  validates :first_name, :last_name, :email, length: { maximum: 50 }
  validates :email,
      uniqueness: { case_sensitive: false },
      presence: true,
      format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def authorize
    redirect_to log_in_url, alert: 'You must be logged in!' unless current_user
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    redirect_to users_url if current_user
  end

  def create
    user = User.find_by_email(params[:email])

    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to users_url, :notice => 'Logged in!'
    else
      flash.now.alert = 'Invalid email or password'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => 'Logged out!'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authorize
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @user = User.all.order(:first_name, :last_name).paginate(:page => params[:page])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to @user, :notice => 'The user was successfully created.'
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to @user, notice: 'The user was successfully updated.'
    else
      render 'edit'
    end
  end

  def show
  end

  def destroy
    @user.destroy
    redirect_to users_url
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flash_helper.rb
module FlashHelper
  def flash_message
    flash[:alert] || flash[:notice]
  end

  def flash_class
    flash[:alert] ? 'alert-danger' : 'alert-info'
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
  # Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: "#{user.first_name} #{user.last_name}", class: "gravatar")
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Batables</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <!--[if lt IE 9]>
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->
</head>
<body>
  <header class="navbar navbar-fixed-top navbar-inverse">
    <div class="navbar-inner">
      <div class="container">
        <%= link_to "Batables", root_url, class: "brand" %>
        <% if current_user %>
          <ul class="nav">
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Admin
              <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to 'Users', users_path %></li>
              </ul>
            </li>
          </ul>
        <% end %>
        <p class="navbar-text pull-right">
          <% if current_user %>
            Logged in as <%= link_to current_user.email, current_user %>. 
            <%= link_to "Log out", log_out_path, data: { method: :delete } %>
          <% else %>
            <%= link_to "Log in", log_in_path %>
          <% end %>
        </p>
      </div>
    </div>
  </header>
  <div class="container">
    <% if flash_message %>
      <div class="alert <%= flash_class %> alert-dismissable fade in">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <strong><%= flash_message %></strong>
      </div>
    <% end %>
    <%= yield %>
    <%= debug(params) if Rails.env.development? %>
  </div>
</body>
</html>

app/views/users/_form.html.erb
<%= simple_form_for @user do |f| %>
  <%= f.error_notification %>

  <fieldset>
    <div class="form-inputs">
      <%= f.input :first_name, input_html: { autofocus: true } %>
      <%= f.input :last_name %>
      <%= f.input :email %>
      <%= f.input :password %>
      <%= f.input :password_confirmation %>
    </div>
    <div class="form-actions">
      <%= f.button :submit, class: 'btn-default' %>
    </div>
  </fieldset>
<% end %>

app/views/users/edit.html.erb
<h1>Edit User</h1>

<%= render 'form' %>

app/views/users/index.html.erb
<h1>User List</h1>

<table class="table table-hover table-condensed">
  <thead>
    <tr>
      <th>First Name</th>
      <th>Last Name</th>
      <th>Email</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @user.each do |user| %>
      <tr>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.email %></td>
        <td><%= link_to '<i class="icon-eye-open"></i>'.html_safe, user_path(user) %></td>
        <td><%= link_to '<i class="icon-pencil"></i>'.html_safe, edit_user_path(user) %></td>
        <td><%= link_to '<i class="icon-trash"></i>'.html_safe, user, method: :delete, data: { confirm: 'Ayer you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= will_paginate @user %>

<br />

<%= link_to 'Create user', new_user_path, class: 'btn btn-default' %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<h1><%= "#{@user.first_name} #{@user.last_name}" %></h1>
<p class="center"><%= gravatar_for @user %></p>
<p>Email: <%= @user.email %></p>

<%= link_to 'User list', users_url %>